#!/bin/sh
grep "gr215" /etc/passwd | awk -F: ' {user[i++]=$3 } 
                                        END {max=user[i]

					 for (j=i;j>=0;j--) 
                      if (user[j]>max) 
						max=user[j]  
					 print(max)    }'
